

obj-$(CONFIG_KERNEL_LIBHWSECUREC) := memcpy_s.o memmove_s.o memset_s.o  strncpy_s.o securecutil.o  strcat_s.o strcpy_s.o strncat_s.o

#snprintf_s.o  vsnprintf_s.o  secureprintoutput_a.o
ccflags-y += -Iinclude/linux/hisilicon/  -DSECUREC_IN_KERNEL

